// Login
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';

//courses
export const FETCH_COURSES_START = 'FETCH_COURSES_START';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAIL = 'FETCH_COURSES_FAIL';
export const FETCH_COURSES = 'FETCH_COURSES';

export const FETCH_COURSE_DETAILS_START = 'FETCH_COURSE_DETAILS_START';
export const FETCH_COURSE_DETAILS_SUCCESS = 'FETCH_COURSE_DETAILS_SUCCESS';
export const FETCH_COURSE_DETAILS_FAIL = 'FETCH_COURSE_DETAILS_FAIL';
export const FETCH_COURSE_DETAILS= 'FETCH_COURSE_DETAILS';

export const FETCH_MODULE_CLASS_START = 'FETCH_MODULE_CLASS_START';
export const FETCH_MODULE_CLASS_SUCCESS = 'FETCH_MODULE_CLASS_SUCCESS';
export const FETCH_MODULE_CLASS_FAIL = 'FETCH_MODULE_CLASS_FAIL';
export const FETCH_MODULE_CLASS= 'FETCH_MODULE_CLASS';


export const ADD_MODULE_CLASS_START = 'ADD_MODULE_CLASS_START';
export const ADD_MODULE_CLASS_SUCCESS = 'ADD_MODULE_CLASS_SUCCESS';
export const ADD_MODULE_CLASS_FAIL = 'ADD_MODULE_CLASS_FAIL';
export const ADD_MODULE_CLASS= 'ADD_MODULE_CLASS';

//students

export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';

export const FETCH_STUDENT_DETAILS_START = 'FETCH_STUDENT_DETAILS_START';
export const FETCH_STUDENT_DETAILS_SUCCESS = 'FETCH_STUDENT_DETAILS_SUCCESS';
export const FETCH_STUDENT_DETAILS_FAIL = 'FETCH_STUDENT_DETAILS_FAIL';
export const FETCH_STUDENT_DETAILS= 'FETCH_STUDENT_DETAILS';

export const DELETE_STUDENT_START = 'DELETE_STUDENT_START';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL';
export const DELETE_STUDENT = 'DELETE_STUDENT'

export const EDIT_STUDENT_START = 'EDIT_STUDENT_START';
export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS';
export const EDIT_STUDENT_FAIL = 'EDIT_STUDENT_FAIL';
export const EDIT_STUDENT = 'EDIT_STUDENT'

export const ADD_STUDENT_ACCOUNT = 'ADD_STUDENT_ACCOUNT';
export const ADD_STUDENT_ACCOUNT_START = 'ADD_STUDENT_ACCOUNT_START';
export const ADD_STUDENT_ACCOUNT_FAIL = 'ADD_STUDENT_ACCOUNT_FAIL';
export const ADD_STUDENT_ACCOUNT_SUCCESS = 'ADD_STUDENT_ACCOUNT_SUCCESS';

//Examinations
export const FETCH_EXAMINATIONS_START = 'FETCH_EXAMINATIONS_START';
export const FETCH_EXAMINATIONS_SUCCESS = 'FETCH_EXAMINATIONS_SUCCESS';
export const FETCH_EXAMINATIONS_FAIL = 'FETCH_EXAMINATIONS_FAIL';
export const FETCH_EXAMINATIONS = 'FETCH_EXAMINATIONS';

export const FETCH_EXAMINATION_DETAILS_START = 'FETCH_EXAMINATION_DETAILS_START';
export const FETCH_EXAMINATION_DETAILS_SUCCESS = 'FETCH_EXAMINATION_DETAILS_SUCCESS';
export const FETCH_EXAMINATION_DETAILS_FAIL = 'FETCH_EXAMINATION_DETAILS_FAIL';
export const FETCH_EXAMINATION_DETAILS = 'FETCH_EXAMINATION_DETAILS';

export const ADD_SHIFT = 'ADD_SHIFT';
export const ADD_SHIFT_START = 'ADD_SHIFT_START';
export const ADD_SHIFT_FAIL = 'ADD_SHIFT_FAIL';
export const ADD_SHIFT_SUCCESS = 'ADD_SHIFT_SUCCESS';